### ISSUE TITLE
??

### ISSUE THREAD

**Issue by tordbb** [acntech/fruit-classifier#1]
Did this:

```
python -m fruit_classifier.preprocessing
```

and got

```
(base) C:\Users\tord.b.brandsaeter\OneDrive - Accenture\Python\fruit-classifier>python -m fruit_classifier.preprocessing
Using TensorFlow backend.
Copying files:   0%|                                                                                        | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\tord.b.brandsaeter\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\tord.b.brandsaeter\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tord.b.brandsaeter\OneDrive - Accenture\Python\fruit-classifier\fruit_classifier\preprocessing\__main__.py", line 25, in <module>
    main()
  File "C:\Users\tord.b.brandsaeter\OneDrive - Accenture\Python\fruit-classifier\fruit_classifier\preprocessing\__main__.py", line 21, in main
    remove_non_images(raw_dir, cleaned_dir)
  File "C:\Users\tord.b.brandsaeter\OneDrive - Accenture\Python\fruit-classifier\fruit_classifier\preprocessing\preprocessing_utils.py", line 21, in remove_non_images
    copytree(str(raw_dir), str(clean_dir))
  File "C:\Users\tord.b.brandsaeter\OneDrive - Accenture\Python\fruit-classifier\fruit_classifier\utils\file_utils.py", line 33, in copytree
    shutil.copytree(s, d, symlinks, ignore)
  File "C:\Users\tord.b.brandsaeter\AppData\Local\Continuum\anaconda3\lib\shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('C:\\Users\\tord.b.brandsaeter\\OneDrive - Accenture\\Python\\fruit-classifier\\generated_data\\raw_data\\apples\\302. apple-nature-plant-fruit-fall-food-green-harvest-produce-crop-autumn-drink-seasonal-apples-liqueur-flowering-plant-rose-family-land-plant-1093429.jpg', 'C:\\Users\\tord.b.brandsaeter\\OneDrive - Accenture\\Python\\fruit-classifier\\generated_data\\cleaned_data\\apples\\302. apple-nature-plant-fruit-fall-food-green-harvest-produce-crop-autumn-drink-seasonal-apples-liqueur-flowering-plant-rose-family-land-plant-1093429.jpg', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\tord.b.brandsaeter\\\\OneDrive - Accenture\\\\Python\\\\fruit-classifier\\\\generated_data\\\\cleaned_data\\\\apples\\\\302. apple-nature-plant-fruit-fall-food-green-harvest-produce-crop-autumn-drink-seasonal-apples-liqueur-flowering-plant-rose-family-land-plant-1093429.jpg'")]
```

**Comment by loeiten** [comment]
Closed by #6

**Comment by tordbb** [comment]
I still got this problem with the files I scraped, since they had long file names.

**Comment by fabiansd** [comment]
Then this must be due to windows  255 character long path limit and should rename the files when scraping.

**Comment by tordbb** [comment]
I agree. I have made a pull request for a fix to this problem.
